import type { AdaptationPolicyId, AdaptationPolicyMetadata } from '@/types/evidence';

export const ADAPTATION_POLICIES: Readonly<Record<AdaptationPolicyId, AdaptationPolicyMetadata>> = {
  goal_prescription: {
    id: 'goal_prescription',
    label: 'Goal prescription',
    summary: 'Base sets, reps, RPE, and loading targets come from the selected training goal.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['goal_load_ranges', 'volume_and_frequency'],
  },
  split_selection: {
    id: 'split_selection',
    label: 'Split selection',
    summary: 'Weekly day count maps to a repeatable split that spreads work across the week.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['split_selection', 'volume_and_frequency'],
  },
  session_time_budget: {
    id: 'session_time_budget',
    label: 'Session time budget',
    summary: 'Time caps reduce exercise count first so core work stays intact when sessions need to stay shorter.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['split_selection', 'volume_and_frequency'],
  },
  exercise_stability: {
    id: 'exercise_stability',
    label: 'Exercise stability window',
    summary: 'Exercises are pinned across the full program so the same movements can progress week to week.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['specificity_and_exercise_stability', 'progressive_overload'],
  },
  compound_priority: {
    id: 'compound_priority',
    label: 'Compound priority',
    summary: 'Compound-friendly slots are prioritized earlier so the highest-value work gets the best placement.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['specificity_and_exercise_stability', 'goal_load_ranges'],
  },
  progressive_overload: {
    id: 'progressive_overload',
    label: 'Progressive overload',
    summary: 'Loading weeks increase weight gradually while keeping rep targets anchored to the chosen goal.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['progressive_overload', 'periodization'],
  },
  deload_cadence: {
    id: 'deload_cadence',
    label: 'Deload cadence',
    summary: 'Every fourth week uses lighter loading and effort to create a simple built-in recovery rhythm.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['deloading', 'periodization'],
  },
  experience_scaling: {
    id: 'experience_scaling',
    label: 'Experience scaling',
    summary: 'Beginner and advanced lifters receive slightly different set and RPE targets to keep the plan recoverable.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['autoregulation', 'goal_load_ranges'],
  },
  cycle_phase_caution: {
    id: 'cycle_phase_caution',
    label: 'Cycle phase caution',
    summary: 'Menstrual and luteal adjustments remain conservative and optional instead of assuming a universal performance drop.',
    category: 'generator',
    defaultSurface: 'program_generation',
    evidenceKeys: ['cycle_phase_adjustments', 'autoregulation'],
  },
};
