import type { EvidenceKey, EvidenceRegistryEntry } from '@/types/evidence';

export const EVIDENCE_REGISTRY: Readonly<Record<EvidenceKey, EvidenceRegistryEntry>> = {
  progressive_overload: {
    key: 'progressive_overload',
    label: 'Progressive overload',
    summary: 'Training stress should increase gradually over time so performance can continue improving.',
    strength: 'strong',
    primarySourceType: 'position_stand',
    sourceRoute: 'research_report',
    surfaces: ['program_generation', 'trust'],
  },
  specificity_and_exercise_stability: {
    key: 'specificity_and_exercise_stability',
    label: 'Specificity and exercise stability',
    summary: 'Primary lifts and movement patterns should stay stable long enough to measure progress clearly.',
    strength: 'strong',
    primarySourceType: 'position_stand',
    sourceRoute: 'research_report',
    surfaces: ['program_generation', 'trust'],
  },
  volume_and_frequency: {
    key: 'volume_and_frequency',
    label: 'Volume and frequency',
    summary: 'Weekly volume matters most, while training frequency mainly helps distribute that work productively.',
    strength: 'strong',
    primarySourceType: 'umbrella_review',
    sourceRoute: 'research_report',
    surfaces: ['program_generation', 'trust'],
  },
  goal_load_ranges: {
    key: 'goal_load_ranges',
    label: 'Goal-specific load and rep ranges',
    summary: 'Different goals favor different rep ranges, effort targets, and loading strategies.',
    strength: 'strong',
    primarySourceType: 'position_stand',
    sourceRoute: 'faq',
    surfaces: ['program_generation', 'faq', 'trust'],
  },
  split_selection: {
    key: 'split_selection',
    label: 'Split selection',
    summary: 'Split choice is mostly a logistics, recoverability, and adherence decision when weekly volume is comparable.',
    strength: 'moderate',
    primarySourceType: 'meta_analysis',
    sourceRoute: 'faq',
    surfaces: ['program_generation', 'faq', 'trust'],
  },
  periodization: {
    key: 'periodization',
    label: 'Periodization',
    summary: 'Structured progression and lighter recovery periods can help manage fatigue and build toward later weeks.',
    strength: 'moderate',
    primarySourceType: 'systematic_review',
    sourceRoute: 'faq',
    surfaces: ['program_generation', 'faq', 'trust'],
  },
  autoregulation: {
    key: 'autoregulation',
    label: 'Autoregulation',
    summary: 'Readiness and recovery signals are useful context, but they should guide conservative adjustments rather than rigid prescriptions.',
    strength: 'moderate',
    primarySourceType: 'research_synthesis',
    sourceRoute: 'faq',
    surfaces: ['readiness', 'faq', 'trust'],
  },
  deloading: {
    key: 'deloading',
    label: 'Deloading',
    summary: 'Deloads are a practical fatigue-management heuristic, but exact timing and structure remain less certain than foundational training principles.',
    strength: 'emerging',
    primarySourceType: 'research_synthesis',
    sourceRoute: 'faq',
    surfaces: ['program_generation', 'faq', 'trust'],
  },
  cycle_phase_adjustments: {
    key: 'cycle_phase_adjustments',
    label: 'Cycle phase adjustments',
    summary: 'Cycle-based training changes should stay optional and conservative because average performance effects are mixed and highly individual.',
    strength: 'mixed',
    primarySourceType: 'consensus_statement',
    sourceRoute: 'research_report',
    surfaces: ['readiness', 'trust'],
  },
  recovery_modalities: {
    key: 'recovery_modalities',
    label: 'Recovery modalities',
    summary: 'Recovery work is most defensible when framed as comfort, mobility, or soreness support rather than a guaranteed performance booster.',
    strength: 'moderate',
    primarySourceType: 'research_synthesis',
    sourceRoute: 'recovery_library',
    surfaces: ['recovery_library', 'trust'],
  },
};
