import { Equipment, MuscleGroup } from '@/types/program';

export interface LocalExercise {
  id: string;
  name: string;
  muscleGroup: MuscleGroup;
  equipment: Equipment;
  defaultSets: number;
  defaultRepMin: number;
  defaultRepMax: number;
  defaultRPE: number;
  /** suggested_weight_lb = userBodyweight × bodyweightMultiplier. Use 0 for pure bodyweight exercises. */
  bodyweightMultiplier: number;
  experienceMultipliers: {
    beginner: number;
    intermediate: number;
    advanced: number;
  };
}

// ─── Chest ────────────────────────────────────────────────────────────────────

const chestExercises: LocalExercise[] = [
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    muscleGroup: 'Chest',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 6,
    defaultRepMax: 10,
    defaultRPE: 8,
    bodyweightMultiplier: 0.65,
    experienceMultipliers: { beginner: 0.60, intermediate: 0.85, advanced: 1.10 },
  },
  {
    id: 'dumbbell-incline-press',
    name: 'Dumbbell Incline Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.20,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    muscleGroup: 'Chest',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.20,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'dumbbell-chest-press',
    name: 'Dumbbell Chest Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.22,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    muscleGroup: 'Chest',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-decline-press',
    name: 'Dumbbell Decline Press',
    muscleGroup: 'Chest',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.22,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
];

// ─── Back ─────────────────────────────────────────────────────────────────────

const backExercises: LocalExercise[] = [
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    muscleGroup: 'Back',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 6,
    defaultRepMax: 10,
    defaultRPE: 8,
    bodyweightMultiplier: 0.60,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.50,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.45,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-single-arm-row',
    name: 'Dumbbell Single-Arm Row',
    muscleGroup: 'Back',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.25,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    muscleGroup: 'Back',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 5,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'cable-straight-arm-pulldown',
    name: 'Cable Straight-Arm Pulldown',
    muscleGroup: 'Back',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.25,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
];

// ─── Shoulders ────────────────────────────────────────────────────────────────

const shoulderExercises: LocalExercise[] = [
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    muscleGroup: 'Shoulders',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 6,
    defaultRepMax: 10,
    defaultRPE: 8,
    bodyweightMultiplier: 0.55,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0.07,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
  {
    id: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raise',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.08,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
  {
    id: 'cable-face-pull',
    name: 'Cable Face Pull',
    muscleGroup: 'Shoulders',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0.18,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    muscleGroup: 'Shoulders',
    equipment: 'Machine',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.45,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-arnold-press',
    name: 'Dumbbell Arnold Press',
    muscleGroup: 'Shoulders',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.14,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
];

// ─── Biceps ───────────────────────────────────────────────────────────────────

const bicepsExercises: LocalExercise[] = [
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.30,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.12,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    muscleGroup: 'Biceps',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.22,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'dumbbell-concentration-curl',
    name: 'Dumbbell Concentration Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.10,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    muscleGroup: 'Biceps',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.10,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    muscleGroup: 'Biceps',
    equipment: 'Barbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.25,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
];

// ─── Triceps ──────────────────────────────────────────────────────────────────

const tricepsExercises: LocalExercise[] = [
  {
    id: 'cable-tricep-pushdown',
    name: 'Tricep Pushdown (Cable)',
    muscleGroup: 'Triceps',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.28,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'dumbbell-skull-crusher',
    name: 'Dumbbell Skull Crusher',
    muscleGroup: 'Triceps',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.13,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close-Grip Bench Press',
    muscleGroup: 'Triceps',
    equipment: 'Barbell',
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 10,
    defaultRPE: 8,
    bodyweightMultiplier: 0.55,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    muscleGroup: 'Triceps',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.15,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'dip',
    name: 'Dip',
    muscleGroup: 'Triceps',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 15,
    defaultRPE: 8,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'cable-overhead-tricep-extension',
    name: 'Cable Overhead Tricep Extension',
    muscleGroup: 'Triceps',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.20,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
];

// ─── Legs ─────────────────────────────────────────────────────────────────────

const legsExercises: LocalExercise[] = [
  {
    id: 'barbell-squat',
    name: 'Barbell Squat',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 5,
    defaultRepMax: 8,
    defaultRPE: 8,
    bodyweightMultiplier: 0.75,
    experienceMultipliers: { beginner: 0.60, intermediate: 0.85, advanced: 1.15 },
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.70,
    experienceMultipliers: { beginner: 0.60, intermediate: 0.85, advanced: 1.10 },
  },
  {
    id: 'leg-press-machine',
    name: 'Leg Press (Machine)',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 1.20,
    experienceMultipliers: { beginner: 0.60, intermediate: 0.85, advanced: 1.10 },
  },
  {
    id: 'dumbbell-lunge',
    name: 'Dumbbell Lunge',
    muscleGroup: 'Legs',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.18,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'leg-extension-machine',
    name: 'Leg Extension (Machine)',
    muscleGroup: 'Legs',
    equipment: 'Machine',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.45,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'barbell-front-squat',
    name: 'Barbell Front Squat',
    muscleGroup: 'Legs',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 5,
    defaultRepMax: 8,
    defaultRPE: 8,
    bodyweightMultiplier: 0.60,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
];

// ─── Glutes ───────────────────────────────────────────────────────────────────

const glutesExercises: LocalExercise[] = [
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    muscleGroup: 'Glutes',
    equipment: 'Barbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.70,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.10 },
  },
  {
    id: 'cable-kickback',
    name: 'Cable Kickback',
    muscleGroup: 'Glutes',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0.15,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
  {
    id: 'dumbbell-step-up',
    name: 'Dumbbell Step-Up',
    muscleGroup: 'Glutes',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    defaultRPE: 7,
    bodyweightMultiplier: 0.16,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.70, advanced: 0.90 },
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    muscleGroup: 'Glutes',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 15,
    defaultRepMax: 25,
    defaultRPE: 6,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    muscleGroup: 'Glutes',
    equipment: 'Barbell',
    defaultSets: 3,
    defaultRepMin: 5,
    defaultRepMax: 8,
    defaultRPE: 8,
    bodyweightMultiplier: 0.80,
    experienceMultipliers: { beginner: 0.60, intermediate: 0.85, advanced: 1.15 },
  },
  {
    id: 'machine-hip-abduction',
    name: 'Machine Hip Abduction',
    muscleGroup: 'Glutes',
    equipment: 'Machine',
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0.35,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
];

// ─── Core ─────────────────────────────────────────────────────────────────────

const coreExercises: LocalExercise[] = [
  {
    id: 'plank',
    name: 'Plank',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 30,  // seconds
    defaultRepMax: 60,
    defaultRPE: 7,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    muscleGroup: 'Core',
    equipment: 'Cable',
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0.25,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 15,
    defaultRPE: 8,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    muscleGroup: 'Core',
    equipment: 'Other',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 15,
    defaultRPE: 8,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    muscleGroup: 'Core',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 15,
    defaultRepMax: 25,
    defaultRPE: 7,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-side-bend',
    name: 'Dumbbell Side Bend',
    muscleGroup: 'Core',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 20,
    defaultRPE: 6,
    bodyweightMultiplier: 0.10,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.65, advanced: 0.85 },
  },
];

// ─── Full Body ────────────────────────────────────────────────────────────────

const fullBodyExercises: LocalExercise[] = [
  {
    id: 'deadlift',
    name: 'Deadlift',
    muscleGroup: 'Full Body',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 3,
    defaultRepMax: 6,
    defaultRPE: 9,
    bodyweightMultiplier: 0.90,
    experienceMultipliers: { beginner: 0.65, intermediate: 0.90, advanced: 1.20 },
  },
  {
    id: 'barbell-clean',
    name: 'Barbell Clean',
    muscleGroup: 'Full Body',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 3,
    defaultRepMax: 5,
    defaultRPE: 8,
    bodyweightMultiplier: 0.60,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    muscleGroup: 'Full Body',
    equipment: 'Kettlebell',
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 20,
    defaultRPE: 7,
    bodyweightMultiplier: 0.22,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'burpee',
    name: 'Burpee',
    muscleGroup: 'Full Body',
    equipment: 'Bodyweight',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 15,
    defaultRPE: 8,
    bodyweightMultiplier: 0,
    experienceMultipliers: { beginner: 0.50, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'dumbbell-thruster',
    name: 'Dumbbell Thruster',
    muscleGroup: 'Full Body',
    equipment: 'Dumbbell',
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    defaultRPE: 8,
    bodyweightMultiplier: 0.18,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.75, advanced: 1.00 },
  },
  {
    id: 'barbell-power-clean',
    name: 'Barbell Power Clean',
    muscleGroup: 'Full Body',
    equipment: 'Barbell',
    defaultSets: 4,
    defaultRepMin: 3,
    defaultRepMax: 5,
    defaultRPE: 8,
    bodyweightMultiplier: 0.55,
    experienceMultipliers: { beginner: 0.55, intermediate: 0.80, advanced: 1.05 },
  },
];

// ─── Master record ────────────────────────────────────────────────────────────

export const exercisesByMuscleGroup: Record<MuscleGroup, LocalExercise[]> = {
  Chest: chestExercises,
  Back: backExercises,
  Shoulders: shoulderExercises,
  Biceps: bicepsExercises,
  Triceps: tricepsExercises,
  Legs: legsExercises,
  Glutes: glutesExercises,
  Core: coreExercises,
  'Full Body': fullBodyExercises,
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns all exercises for the given muscle group, optionally excluding
 * exercises whose IDs appear in `excludeIds`.
 */
export function getAlternativesFor(
  muscleGroup: MuscleGroup,
  excludeIds: string[] = [],
): LocalExercise[] {
  const exercises = exercisesByMuscleGroup[muscleGroup] ?? [];
  if (excludeIds.length === 0) return exercises;
  const excluded = new Set(excludeIds);
  return exercises.filter((ex) => !excluded.has(ex.id));
}
